"""init_schema

Revision ID: 5ff7de97baea
Revises:
Create Date: 2025-11-19 12:54:02.413116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ff7de97baea"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("profile_url", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("user_profiles_pkey")),
        sa.UniqueConstraint("profile_url", name=op.f("user_profiles_profile_url_key")),
        sa.UniqueConstraint("username", name=op.f("user_profiles_username_key")),
    )
    op.create_table(
        "user_stats",
        sa.Column("game_type", sa.String(length=50), nullable=False),
        sa.Column("games_played", sa.Integer(), nullable=False),
        sa.Column("games_won", sa.Integer(), nullable=False),
        sa.Column("highest_rating", sa.Integer(), nullable=True),
        sa.Column("current_rating", sa.Integer(), nullable=True),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["user_profiles.id"], name=op.f("user_stats_profile_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("user_stats_pkey")),
        sa.UniqueConstraint("profile_id", "game_type", name=op.f("user_stats_profile_id_game_type_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_stats")
    op.drop_table("user_profiles")
    # ### end Alembic commands ###
